# -*- coding: utf-8 -*-
"""diabetes_knn_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mUbfhkv5AWB34Z4BnVuXlKc6MO8Q_i91
"""

from google.colab import drive
drive.mount('/content/drive')

dosya_yolu = '/content/drive/MyDrive/Colab Notebooks/diabetes/diabetes.csv'

# Gerekli kütüphaneleri yükleme
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, roc_curve, roc_auc_score, accuracy_score, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
import seaborn as sns
import numpy as np

# Veri setini yükleme
df = pd.read_csv(dosya_yolu)

# Veri setini görüntüleme
df.head()

# Veri seti kolon isimleri
df.columns

# Veri seti kolon veritipleri
df.info()

# satır ve sütun sayıları
df.shape

# kolonlara ait istatistiki bilgiler
df.describe()

# kolonlarda boş değerler var mı
df.isnull().sum()

# 1 ve 0 lardan oluşan sonuç kümem de bulunan 0 ve 1 lerin sayısal grafiği
sns.countplot(x='Outcome',data=df,palette=['b','g'])

# veri setindeki değişkenler arasındaki ilişkileri görselleştirmek
sns.pairplot(data=df,hue='Outcome')
plt.show()

# Özellikler ve hedef değişkeni ayırma
X = df.drop(["Outcome"], axis=1)
y = df["Outcome"]

# Eğitim ve test setlerine ayırma
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# KNN algoritmasını uygulama
knn = KNeighborsClassifier(n_neighbors=10) # Komşu sayısını 8 olarak belirledik

# Modeli eğitme
knn.fit(X_train, y_train)

# test verilerindeki girdiler için sınıf tahminleri yapmak
y_predict=knn.predict(X_test)
y_predict

# confusion matris
cm1=confusion_matrix(y_test,y_predict)
cm1

# Modelin doğruluğunu test etme
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Model doğruluğu: ", accuracy)

# Performans metriklerinin hesaplanması
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

# Performans metriklerini ekrana yazdırma
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

# ROC eğrisi ve AUC değeri
y_pred_prob = knn.predict_proba(X_test)[:, 1]
fpr, tpr, thresholds = roc_curve(y_test, y_pred_prob)
roc_auc = roc_auc_score(y_test, y_pred_prob)

# ROC grafiği çizimi
plt.plot(fpr, tpr, label='ROC Curve (AUC = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], 'k--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend(loc="lower right")
plt.show()

# KNN modelini eğit ve test et
# birden fazla k değerini test etme
accuracy = []
for k in range(1, 10):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    score = knn.score(X_test, y_test)
    accuracy.append(score)

# Grafik olarak çiz
plt.plot(range(1, 10), accuracy)
plt.xlabel('K değeri')
plt.ylabel('Doğruluk')
plt.title('KNN algoritmasının doğruluğu')
plt.show()

# Örnek bir girdi için sonuç tahmini
example_input = [8,99,84,0,0,35.4,0.388,50] #0
predicted_class = knn.predict([example_input])[0]
print("Tahmin edilen sınıf: ", predicted_class)

# Örnek bir girdi için sonuç tahmini
example_input = [6,148,72,35,0,33.6,0.627,50] #1
predicted_class = knn.predict([example_input])[0]
print("Tahmin edilen sınıf: ", predicted_class)

# Sonuc 1 olması gerekirken 0 olarak tahmin ediliyor. !!

# Örnek bir girdi için sonuç tahmini
example_input = [1,89,66,23,94,28.1,0.167,21] #0
predicted_class = knn.predict([example_input])[0]
print("Tahmin edilen sınıf: ", predicted_class)

# Örnek bir girdi için sonuç tahmini
example_input = [5,166,72,19,175,25.8,0.587,51] #1
predicted_class = knn.predict([example_input])[0]
print("Tahmin edilen sınıf: ", predicted_class)